// ==UserScript==
// @name            Reopen Closed Tabs Menu
// @description     A popup menu to view and restore recently closed tabs. Includes a toolbar button and keyboard shortcut.
// @author          Bibek Bhusal
// @version         1.1.4
// @lastUpdated     2026-06-21
// @ignorecache
// @homepage        https://github.com/Vertex-Mods/Reopen-Closed-Tabs-Menu
// ==/UserScript==

// This file was automatically generated. Do not edit this file directly.
// Any changes made here will be overwritten.
// To make changes, please edit the source files in the repository:
// https://github.com/BibekBhusal0/zen-custom-js

(() => {

  // utils/pref.js
  function setPref(key, value) {
    try {
      let prefService = Services.prefs;
      if (typeof value === "boolean")
        prefService.setBoolPref(key, value);
      else if (typeof value === "number")
        prefService.setIntPref(key, value);
      else
        prefService.setStringPref(key, value);
    } catch {}
  }
  var getPref = (key, defaultValue) => {
    try {
      let prefService = Services.prefs, type = prefService.getPrefType(key);
      if (type === prefService.PREF_STRING)
        return prefService.getStringPref(key);
      else if (type === prefService.PREF_INT)
        return prefService.getIntPref(key);
      else if (type === prefService.PREF_BOOL)
        return prefService.getBoolPref(key);
      return defaultValue;
    } catch {
      return defaultValue;
    }
  }, setPrefIfUnset = (key, value) => {
    if (Services.prefs.getPrefType(key) === 0)
      setPref(key, value);
  };
  function addPrefListener(name, callback) {
    let modified_callback = () => {
      callback({ value: getPref(name) });
    };
    return Services.prefs.addObserver(name, modified_callback), { name, callback };
  }
  class PREFS {
    static MOD_NAME = "BasePrefs";
    static DEBUG_MODE = "";
    static defaultValues = {};
    static getPref(key, defaultValue = void 0) {
      let defaultVal = defaultValue !== void 0 ? defaultValue : this.defaultValues[key];
      return getPref(key, defaultVal);
    }
    static setPref(prefKey, value) {
      setPref(prefKey, value);
    }
    static setInitialPrefs() {
      for (let [key, value] of Object.entries(this.defaultValues))
        setPrefIfUnset(key, value);
    }
    static get debugMode() {
      if (!this.DEBUG_MODE)
        return !1;
      return this.getPref(this.DEBUG_MODE);
    }
    static set debugMode(value) {
      if (!this.DEBUG_MODE)
        return;
      this.setPref(this.DEBUG_MODE, value);
    }
    static debugLog(...args) {
      if (this.debugMode)
        console.log(`${this.MOD_NAME}:`, ...args);
    }
    static debugError(...args) {
      if (this.debugMode)
        console.error(`${this.MOD_NAME}:`, ...args);
    }
  }

  // reopen-closed-tabs/utils/prefs.js
  class ReopenClosedTabsPREFS extends PREFS {
    static MOD_NAME = "ReopenClosedTabs";
    static DEBUG_MODE = "extensions.reopen-closed-tabs.debug-mode";
    static SHORTCUT_KEY = "extensions.reopen-closed-tabs.shortcut-key";
    static SHOW_OPEN_TABS = "extensions.reopen-closed-tabs.show-open-tabs";
    static SHOW_SYNC_TABS = "extensions.reopen-closed-tabs.show-sync-tabs";
    static defaultValues = {
      [ReopenClosedTabsPREFS.DEBUG_MODE]: !1,
      [ReopenClosedTabsPREFS.SHORTCUT_KEY]: "Alt+A",
      [ReopenClosedTabsPREFS.SHOW_OPEN_TABS]: !1,
      [ReopenClosedTabsPREFS.SHOW_SYNC_TABS]: !0
    };
    static get shortcutKey() {
      return this.getPref(this.SHORTCUT_KEY);
    }
    static set shortcutKey(value) {
      this.setPref(this.SHORTCUT_KEY, value);
    }
    static get showOpenTabs() {
      return this.getPref(this.SHOW_OPEN_TABS);
    }
    static set showOpenTabs(value) {
      this.setPref(this.SHOW_OPEN_TABS, value);
    }
    static get showSyncTabs() {
      return this.getPref(this.SHOW_SYNC_TABS);
    }
    static set showSyncTabs(value) {
      this.setPref(this.SHOW_SYNC_TABS, value);
    }
  }
  var PREFS2 = ReopenClosedTabsPREFS;

  // utils/keyboard.js
  function normalizeKeyName(key) {
    if (!key)
      return "";
    let k = key.toLowerCase();
    if (k === " " || k === "space" || k === "spacebar")
      return "space";
    return k;
  }
  function shortcutStringToSignature(shortcutStr) {
    if (!shortcutStr)
      return "";
    return shortcutStr.toLowerCase().replace(/control/g, "ctrl").replace(/option/g, "alt").split("+").map((s) => normalizeKeyName(s.trim())).join("+");
  }
  var _shortcuts = /* @__PURE__ */ new Map;
  function registerShortcut(shortcutStr, id, callback) {
    if (!shortcutStr || !id || typeof callback !== "function")
      return console.error("registerShortcutInRegistry: Invalid arguments", { shortcutStr, id, callback }), !1;
    unregisterShortcutById(id);
    let signature = shortcutStringToSignature(shortcutStr);
    return _shortcuts.set(signature, { id, callback, shortcutStr }), !0;
  }
  function unregisterShortcutById(id) {
    for (let [signature, shortcut] of _shortcuts.entries())
      if (shortcut.id === id)
        return _shortcuts.delete(signature), !0;
    return !1;
  }

  // utils/parse.js
  var parseElement = (elementString, type = "html") => {
    if (type === "xul")
      return window.MozXULElement.parseXULToFragment(elementString).firstChild;
    let element = new DOMParser().parseFromString(elementString, "text/html");
    if (element.body.children.length)
      element = element.body.firstChild;
    else
      element = element.head.firstChild;
    return element;
  }, escapeXmlAttribute = (str) => {
    if (typeof str !== "string")
      return str;
    return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
  };

  // utils/timesAgo.js
  function timeAgo(timestamp) {
    if (timestamp === 1 / 0)
      return "Now";
    let now = /* @__PURE__ */ new Date, then = new Date(timestamp), seconds = Math.round((now - then) / 1000), minutes = Math.round(seconds / 60), hours = Math.round(minutes / 60), days = Math.round(hours / 24), weeks = Math.round(days / 7), months = Math.round(days / 30.44), years = Math.round(days / 365.25);
    if (seconds < 5)
      return "Just now";
    if (seconds < 60)
      return `${seconds} seconds ago`;
    if (minutes < 60)
      return `${minutes} minutes ago`;
    if (hours < 24)
      return `${hours} hours ago`;
    if (days === 1)
      return "Yesterday";
    if (days < 7)
      return `${days} days ago`;
    if (weeks === 1)
      return "1 week ago";
    if (weeks < 4)
      return `${weeks} weeks ago`;
    if (months === 1)
      return "1 month ago";
    if (months < 12)
      return `${months} months ago`;
    if (years === 1)
      return "1 year ago";
    return `${years} years ago`;
  }

  // reopen-closed-tabs/utils/tab-manager.js
  var TabManager = {
    async getRecentlyClosedTabs() {
      PREFS2.debugLog("Fetching recently closed tabs.");
      try {
        if (typeof SessionStore < "u" && SessionStore.getClosedTabData) {
          let closedTabs = SessionStore.getClosedTabData(window).map((tab, index) => {
            return {
              url: tab.state.entries[0]?.url,
              title: tab.title || tab.state.entries[0]?.title,
              isClosed: !0,
              sessionData: tab,
              sessionIndex: index,
              faviconUrl: tab.image,
              closedAt: tab.closedAt
            };
          }).sort((a, b) => b.closedAt - a.closedAt);
          return PREFS2.debugLog("Recently closed tabs fetched:", closedTabs), closedTabs;
        } else
          return PREFS2.debugError("SessionStore.getClosedTabData not available."), [];
      } catch (e) {
        return PREFS2.debugError("Error fetching recently closed tabs:", e), [];
      }
    },
    async getSyncedTabs() {
      PREFS2.debugLog("Fetching synced tabs.");
      try {
        let { SyncedTabs } = ChromeUtils.importESModule("resource://services-sync/SyncedTabs.sys.mjs");
        if (!SyncedTabs)
          return PREFS2.debugError("SyncedTabs module not available."), [];
        await SyncedTabs.syncTabs();
        let clients = await SyncedTabs.getTabClients(), syncedTabs = [];
        for (let client of clients)
          for (let tab of client.tabs)
            syncedTabs.push({
              url: tab.url,
              title: tab.title,
              isClosed: !1,
              isSynced: !0,
              clientName: client.name,
              faviconUrl: tab.icon,
              lastUsed: tab.lastUsed
            });
        return syncedTabs.sort((a, b) => b.lastUsed - a.lastUsed), PREFS2.debugLog("Synced tabs fetched:", syncedTabs), syncedTabs;
      } catch (e) {
        return PREFS2.debugError("Error fetching synced tabs:", e), [];
      }
    },
    removeClosedTab(tabData) {
      PREFS2.debugLog("Removing closed tab from session store:", tabData);
      try {
        if (typeof SessionStore < "u" && SessionStore.forgetClosedTab)
          SessionStore.forgetClosedTab(window, tabData.sessionIndex), PREFS2.debugLog("Closed tab removed successfully.");
        else
          PREFS2.debugError("SessionStore.forgetClosedTab not available.");
      } catch (e) {
        PREFS2.debugError("Error removing closed tab:", e);
      }
    },
    _getFolderBreadcrumbs(group) {
      let path = [], currentGroup = group;
      while (currentGroup && currentGroup.isZenFolder)
        path.unshift(currentGroup.label), currentGroup = currentGroup.group;
      return path.join(" / ");
    },
    async getOpenTabs() {
      PREFS2.debugLog("Fetching open tabs.");
      let openTabs = [];
      try {
        let workspaceTabs = gZenWorkspaces.allStoredTabs, essentialTabs = Array.from(document.querySelectorAll('tab[zen-essential="true"]')), allTabs = [.../* @__PURE__ */ new Set([...workspaceTabs, ...essentialTabs])];
        for (let tab of allTabs) {
          if (tab.hasAttribute("zen-empty-tab") || tab.closing)
            continue;
          let isEssential = tab.hasAttribute("zen-essential"), browser = tab.linkedBrowser, workspaceId = tab.getAttribute("zen-workspace-id"), workspace = workspaceId && gZenWorkspaces.getWorkspaceFromId(workspaceId), folder = tab.group?.isZenFolder ? this._getFolderBreadcrumbs(tab.group) : null, tabInfo = {
            id: tab.id,
            url: browser.currentURI.spec,
            title: browser.contentTitle || tab.label,
            isPinned: tab.pinned,
            isEssential,
            folder,
            workspace: isEssential ? void 0 : workspace?.name,
            isClosed: !1,
            faviconUrl: tab.image,
            tabElement: tab,
            lastAccessed: tab._lastAccessed,
            isUnloaded: tab.hasAttribute("pending")
          };
          openTabs.push(tabInfo);
        }
        return openTabs.sort((a, b) => b.lastAccessed - a.lastAccessed), PREFS2.debugLog("Open tabs fetched:", openTabs), openTabs;
      } catch (e) {
        return PREFS2.debugError("Error fetching open tabs:", e), [];
      }
    },
    async reopenTab(tabData) {
      PREFS2.debugLog("Reopening tab:", tabData);
      try {
        if (!tabData.isClosed && tabData.tabElement) {
          let tab = tabData.tabElement;
          gZenWorkspaces.switchTabIfNeeded(tab);
          return;
        }
        if (tabData.isClosed && tabData.sessionData) {
          let tabState = tabData.sessionData.state, url = tabState.entries[0]?.url;
          if (!url) {
            PREFS2.debugError("Cannot reopen tab: URL not found in session data.", tabData);
            return;
          }
          let newTab = gBrowser.addTab(url, {
            triggeringPrincipal: Services.scriptSecurityManager.getSystemPrincipal(),
            userContextId: tabState.userContextId || 0,
            skipAnimation: !0
          });
          gBrowser.selectedTab = newTab, this.removeClosedTab(tabData);
          let workspaceId = tabState.zenWorkspace, activeWorkspaceId = gZenWorkspaces.activeWorkspace;
          if (workspaceId && workspaceId !== activeWorkspaceId)
            await gZenWorkspaces.changeWorkspaceWithID(workspaceId), gZenWorkspaces.moveTabToWorkspace(newTab, workspaceId);
          if (tabState.pinned)
            gBrowser.pinTab(newTab);
          let groupId = tabData.sessionData.closedInTabGroupId;
          if (groupId) {
            let folder = document.getElementById(groupId);
            if (folder && typeof folder.addTabs === "function")
              folder.addTabs([newTab]);
          }
          gBrowser.selectedTab = newTab;
          return;
        }
        if (tabData.url) {
          let newTab = gBrowser.addTab(tabData.url, {
            triggeringPrincipal: Services.scriptSecurityManager.getSystemPrincipal()
          });
          gBrowser.selectedTab = newTab;
        } else
          PREFS2.debugError("Cannot reopen tab: missing URL or session data.", tabData);
      } catch (e) {
        PREFS2.debugError("Error reopening tab:", e);
      }
    }
  }, tab_manager_default = TabManager;

  // utils/startup-finish.js
  function startupFinish(callback) {
    if (document.readyState === "complete")
      callback();
    else
      window.addEventListener("load", callback, { once: !0 });
  }

  // utils/widget.js
  var lazy = {};
  function defineModuleGettersWithFallback(target, modules) {
    for (let [key, spec] of Object.entries(modules))
      Object.defineProperty(target, key, {
        configurable: !0,
        enumerable: !0,
        get: function() {
          try {
            let module = ChromeUtils.importESModule(spec.url);
            return delete target[key], target[key] = module[key], module[key];
          } catch {
            let module = ChromeUtils.importESModule(spec.fallback);
            return delete target[key], target[key] = module[key], module[key];
          }
        }
      });
  }
  defineModuleGettersWithFallback(lazy, {
    CustomizableUI: {
      url: "moz-src:///browser/components/customizableui/CustomizableUI.sys.mjs",
      fallback: "resource:///modules/CustomizableUI.sys.mjs"
    }
  });
  function addWidget(options) {
    try {
      lazy.CustomizableUI.createWidget({
        id: options.id,
        defaultArea: options.defaultArea || lazy.CustomizableUI.AREA_NAVBAR,
        removable: !0,
        label: options.label,
        tooltiptext: options.tooltiptext || options.label,
        onCreated: function(node) {
          if (options.icon)
            node.style.listStyleImage = `url("${options.icon}")`;
          if (options.class)
            node.classList.add(...options.class.split(" "));
          if (options.onClick)
            node.addEventListener("command", (e) => {
              options.onClick(e);
            });
          if (options.onCreated)
            options.onCreated(node);
        }
      });
    } catch {}
  }

  // reopen-closed-tabs/index.js
  var ReopenClosedTabs = {
    _boundToggleMenu: null,
    _boundHandleItemClick: null,
    _allTabsCache: [],
    async init() {
      PREFS2.debugLog("Initializing mod."), PREFS2.setInitialPrefs(), this._boundToggleMenu = this.toggleMenu.bind(this), this._boundHandleItemClick = this._handleItemClick.bind(this), this._registerKeyboardShortcut(), this._registerToolbarButton(), addPrefListener(PREFS2.SHORTCUT_KEY, this.onHotkeyChange.bind(this)), PREFS2.debugLog("Mod initialized.");
    },
    _registerKeyboardShortcut() {
      let shortcutString = PREFS2.shortcutKey;
      if (!shortcutString) {
        PREFS2.debugLog("No shortcut key defined.");
        return;
      }
      if (registerShortcut(shortcutString, "reopen-closed-tabs-hotkey", this._boundToggleMenu).success)
        PREFS2.debugLog(`Registered shortcut: ${shortcutString}`);
      else
        PREFS2.debugError("Failed to register keyboard shortcut");
    },
    onHotkeyChange() {
      this._registerKeyboardShortcut(), PREFS2.debugLog("Registered new shortcut");
    },
    _registerToolbarButton() {
      try {
        addWidget({
          id: "reopen-closed-tabs-button",
          label: "Reopen Closed Tabs",
          tooltiptext: "View and reopen recently closed tabs",
          icon: "chrome://browser/skin/zen-icons/history.svg",
          onClick: this.toggleMenu.bind(this)
        }), PREFS2.debugLog("Registered toolbar button: reopen-closed-tabs-button");
      } catch (e) {
        PREFS2.debugError("Failed to register toolbar button:", e);
      }
    },
    async toggleMenu(event) {
      PREFS2.debugLog("Toggle menu called.");
      let button;
      if (event && event.target && event.target.id === "reopen-closed-tabs-button")
        button = event.target;
      else
        button = document.getElementById("reopen-closed-tabs-button");
      if (!button) {
        PREFS2.debugError("Reopen Closed Tabs button not found.");
        return;
      }
      let panelId = "reopen-closed-tabs-panel";
      if (!button._reopenClosedTabsPanel) {
        let panel2 = parseElement(`
        <panel id="${panelId}" type="arrow">
        </panel>
      `, "xul"), mainPopupSet = document.getElementById("mainPopupSet");
        if (mainPopupSet)
          mainPopupSet.appendChild(panel2), button._reopenClosedTabsPanel = panel2, PREFS2.debugLog(`Created panel: ${panelId} for button: ${button.id}`);
        else {
          PREFS2.debugError("Could not find #mainPopupSet to append panel.");
          return;
        }
      }
      let panel = button._reopenClosedTabsPanel;
      if (panel.state === "open")
        panel.hidePopup();
      else
        await this._populatePanel(panel), panel.openPopup(button, "after_start", 0, 0, !1, !1);
    },
    async _populatePanel(panel) {
      PREFS2.debugLog("Populating panel.");
      while (panel.firstChild)
        panel.removeChild(panel.firstChild);
      let mainVbox = parseElement('<vbox flex="1"/>', "xul");
      panel.appendChild(mainVbox);
      let searchBox = parseElement(`
      <div id="reopen-closed-tabs-search-container">
        <img src="chrome://global/skin/icons/search-glass.svg" class="search-icon"/>
        <input id="reopen-closed-tabs-search-input" type="search" placeholder="Search tabs..."/>
      </div>
    `, "html");
      mainVbox.appendChild(searchBox);
      let allItemsContainer = parseElement('<vbox id="reopen-closed-tabs-list-container" flex="1" />', "xul");
      mainVbox.appendChild(allItemsContainer);
      let showOpenTabs = PREFS2.showOpenTabs, closedTabs = await tab_manager_default.getRecentlyClosedTabs(), openTabs = [];
      if (showOpenTabs)
        openTabs = await tab_manager_default.getOpenTabs();
      if (closedTabs.length > 0)
        this._renderGroup(allItemsContainer, "Recently Closed", closedTabs);
      if (openTabs.length > 0)
        this._renderGroup(allItemsContainer, "Open Tabs", openTabs);
      if (closedTabs.length === 0 && openTabs.length === 0) {
        let noTabsItem = parseElement('<label class="reopen-closed-tab-item-disabled" value="No tabs to display."/>', "xul");
        allItemsContainer.appendChild(noTabsItem);
      }
      this._allTabsCache = [...closedTabs, ...openTabs];
      let firstItem = allItemsContainer.querySelector(".reopen-closed-tab-item");
      if (firstItem)
        firstItem.setAttribute("selected", "true");
      let searchInput = panel.querySelector("#reopen-closed-tabs-search-input");
      if (searchInput)
        searchInput.addEventListener("input", (event) => this._filterTabs(event.target.value, panel)), searchInput.addEventListener("keydown", (event) => this._handleSearchKeydown(event, panel)), panel.addEventListener("popupshown", () => {
          searchInput.focus();
          let listContainer = panel.querySelector("#reopen-closed-tabs-list-container");
          if (listContainer)
            listContainer.scrollTop = 0;
        }, { once: !0 });
      if (PREFS2.showSyncTabs)
        this._loadSyncedTabsAsync(allItemsContainer, panel);
    },
    async _loadSyncedTabsAsync(container, panel) {
      let syncedTabs = await tab_manager_default.getSyncedTabs();
      if (syncedTabs.length === 0)
        return;
      this._renderGroup(container, "Synced Tabs", syncedTabs), this._allTabsCache.push(...syncedTabs);
      let searchInput = panel.querySelector("#reopen-closed-tabs-search-input");
      if (searchInput && searchInput.value) {
        this._filterTabs(searchInput.value, panel);
        return;
      }
      let noTabsItem = container.querySelector(".reopen-closed-tab-item-disabled");
      if (noTabsItem)
        noTabsItem.remove();
      if (!container.querySelector(".reopen-closed-tab-item[selected]")) {
        let firstItem = container.querySelector(".reopen-closed-tab-item");
        if (firstItem)
          firstItem.setAttribute("selected", "true");
      }
    },
    _renderGroup(container, groupTitle, tabs) {
      let groupHeader = parseElement(`
      <hbox class="reopen-closed-tabs-group-header" align="center">
        <label value="${escapeXmlAttribute(groupTitle)}"/>
      </hbox>
    `, "xul");
      container.appendChild(groupHeader), tabs.forEach((tab) => {
        this._renderTabItem(container, tab);
      });
    },
    _renderTabItem(container, tab) {
      let label = escapeXmlAttribute(tab.title || tab.url || "Untitled Tab"), url = escapeXmlAttribute(tab.url || ""), faviconSrc = escapeXmlAttribute(tab.faviconUrl || "chrome://branding/content/icon32.png"), iconHtml = "";
      if (tab.isEssential)
        iconHtml = '<image class="tab-status-icon" src="chrome://browser/skin/zen-icons/essential-add.svg" />';
      else if (tab.isPinned)
        iconHtml = '<image class="tab-status-icon" src="chrome://browser/skin/zen-icons/pin.svg" />';
      let contextParts = [];
      if (tab.isClosed) {
        if (tab.closedAt)
          contextParts = ["Closed " + timeAgo(tab.closedAt)];
      } else if (tab.isSynced) {
        if (tab.lastUsed)
          contextParts.push(timeAgo(tab.lastUsed));
        if (tab.clientName)
          contextParts.push("From " + escapeXmlAttribute(tab.clientName));
      } else {
        if (tab.lastAccessed)
          contextParts.push(timeAgo(tab.lastAccessed));
        if (tab.workspace)
          contextParts.push(escapeXmlAttribute(tab.workspace));
        if (tab.folder)
          contextParts.push(escapeXmlAttribute(tab.folder));
      }
      let contextLabel = contextParts.join(" ● "), tabItem = parseElement(`
      <hbox class="reopen-closed-tab-item" align="center" tooltiptext="${url}">
        <image class="tab-favicon" src="${faviconSrc}" />
        <vbox class="tab-item-labels" flex="1">
          <label class="tab-item-label" value="${label}"/>
          ${contextLabel ? `<label class="tab-item-context" value="${contextLabel}"/>` : ""}
        </vbox>
        <hbox class="tab-item-status-icons" align="center">
          ${iconHtml}
          ${tab.isClosed ? '<image class="close-button" src="chrome://global/skin/icons/close.svg" tooltiptext="Remove from list" />' : ""}
        </hbox>
      </hbox>
    `, "xul");
      if (tab.isUnloaded)
        tabItem.classList.add("unloaded-tab");
      tabItem.tabData = tab, tabItem.addEventListener("click", this._boundHandleItemClick);
      let closeButton = tabItem.querySelector(".close-button");
      if (closeButton)
        closeButton.addEventListener("click", (event) => this._handleRemoveTabClick(event, tabItem));
      container.appendChild(tabItem);
    },
    _handleRemoveTabClick(event, tabItem) {
      if (event.stopPropagation(), tabItem && tabItem.tabData && tabItem.tabData.isClosed)
        tab_manager_default.removeClosedTab(tabItem.tabData), tabItem.remove(), this._allTabsCache = this._allTabsCache.filter((tab) => tab !== tabItem.tabData);
      else
        PREFS2.debugError("Cannot remove tab: Tab data not found or tab is not closed.", tabItem);
    },
    _filterTabs(query, panel) {
      let lowerQuery = query.toLowerCase(), filteredTabs = this._allTabsCache.filter((tab) => {
        let title = (tab.title || "").toLowerCase(), url = (tab.url || "").toLowerCase(), workspace = (tab.workspace || "").toLowerCase(), folder = (tab.folder || "").toLowerCase(), clientName = (tab.clientName || "").toLowerCase();
        return title.includes(lowerQuery) || url.includes(lowerQuery) || workspace.includes(lowerQuery) || folder.includes(lowerQuery) || clientName.includes(lowerQuery);
      }), tabItemsContainer = panel.querySelector("#reopen-closed-tabs-list-container");
      if (tabItemsContainer) {
        while (tabItemsContainer.firstChild)
          tabItemsContainer.removeChild(tabItemsContainer.firstChild);
        if (filteredTabs.length === 0) {
          let noResultsItem = parseElement('<label class="reopen-closed-tab-item-disabled" value="No matching tabs."/>', "xul");
          tabItemsContainer.appendChild(noResultsItem);
        } else {
          let closedTabs = filteredTabs.filter((t) => t.isClosed), openTabs = filteredTabs.filter((t) => !t.isClosed && !t.isSynced), syncedTabs = filteredTabs.filter((t) => t.isSynced);
          if (closedTabs.length > 0)
            this._renderGroup(tabItemsContainer, "Recently Closed", closedTabs);
          if (openTabs.length > 0)
            this._renderGroup(tabItemsContainer, "Open Tabs", openTabs);
          if (syncedTabs.length > 0)
            this._renderGroup(tabItemsContainer, "Synced Tabs", syncedTabs);
          let firstItem = tabItemsContainer.querySelector(".reopen-closed-tab-item");
          if (firstItem)
            firstItem.setAttribute("selected", "true");
        }
      }
    },
    _handleSearchKeydown(event, panel) {
      event.stopPropagation();
      let tabItemsContainer = panel.querySelector("#reopen-closed-tabs-list-container");
      if (!tabItemsContainer)
        return;
      let currentSelected = tabItemsContainer.querySelector(".reopen-closed-tab-item[selected]"), allItems = Array.from(tabItemsContainer.querySelectorAll(".reopen-closed-tab-item")), nextSelected = null;
      if (event.key === "ArrowDown")
        if (event.preventDefault(), currentSelected) {
          let currentIndex = allItems.indexOf(currentSelected);
          nextSelected = allItems[currentIndex + 1] || allItems[0];
        } else
          nextSelected = allItems[0];
      else if (event.key === "ArrowUp")
        if (event.preventDefault(), currentSelected) {
          let currentIndex = allItems.indexOf(currentSelected);
          nextSelected = allItems[currentIndex - 1] || allItems[allItems.length - 1];
        } else
          nextSelected = allItems[allItems.length - 1];
      else if (event.key === "Enter") {
        if (event.preventDefault(), currentSelected)
          currentSelected.click();
      }
      if (currentSelected)
        currentSelected.removeAttribute("selected");
      if (nextSelected) {
        nextSelected.setAttribute("selected", "true"), nextSelected.scrollIntoView({ block: "nearest" });
        let stickyHeader = tabItemsContainer.querySelector(".reopen-closed-tabs-group-header");
        if (stickyHeader) {
          let stickyHeaderHeight = stickyHeader.offsetHeight, selectedItemRect = nextSelected.getBoundingClientRect(), containerRect = tabItemsContainer.getBoundingClientRect();
          if (selectedItemRect.top < containerRect.top + stickyHeaderHeight)
            tabItemsContainer.scrollTop -= containerRect.top + stickyHeaderHeight - selectedItemRect.top;
        }
      }
    },
    _handleItemClick(event) {
      let tabItem = event.target;
      while (tabItem && !tabItem.classList.contains("reopen-closed-tab-item"))
        tabItem = tabItem.parentElement;
      if (tabItem && tabItem.tabData) {
        tab_manager_default.reopenTab(tabItem.tabData);
        let panel = tabItem.closest("panel");
        if (panel)
          panel.hidePopup();
        else
          PREFS2.debugError("Could not find parent panel to hide.");
      } else
        PREFS2.debugError("Cannot reopen tab: Tab data not found on menu item.", event.target);
    }
  };
  function setupCommandPaletteIntegration(retryCount = 0) {
    if (window.ZenCommandPalette)
      PREFS2.debugLog("Integrating with Zen Command Palette..."), window.ZenCommandPalette.addCommands([
        {
          key: "reopen:closed-tabs-menu",
          label: "Open Reopen closed tab menu",
          command: () => ReopenClosedTabs.toggleMenu(),
          icon: "chrome://browser/skin/zen-icons/history.svg",
          tags: ["reopen", "tabs", "closed"]
        }
      ]), PREFS2.debugLog("Zen Command Palette integration successful.");
    else if (PREFS2.debugLog("Zen Command Palette not found, retrying in 1000ms"), retryCount < 10)
      setTimeout(() => setupCommandPaletteIntegration(retryCount + 1), 1000);
    else
      PREFS2.debugError("Could not integrate with Zen Command Palette after 10 retries.");
  }
  startupFinish(() => {
    ReopenClosedTabs.init(), setupCommandPaletteIntegration();
  });
})();
